// XcaliburMoon Service Worker
// Generated by xcm-build-this
// Build hash: 189620df6ef31c78

const CACHE_NAME = 'xcm-cache-189620df6ef31c78';

const PRECACHE_URLS = [
    '/',
    '/assets/css/main.css',
    '/assets/favicon.png',
];

self.addEventListener('install', function(event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function(cache) {
            return cache.addAll(PRECACHE_URLS);
        }).then(function() {
            return self.skipWaiting();
        })
    );
});

self.addEventListener('activate', function(event) {
    event.waitUntil(
        caches.keys().then(function(cacheNames) {
            return Promise.all(
                cacheNames.filter(function(name) {
                    return name !== CACHE_NAME;
                }).map(function(name) {
                    return caches.delete(name);
                })
            );
        }).then(function() {
            return self.clients.claim();
        })
    );
});

self.addEventListener('fetch', function(event) {
    if (event.request.method !== 'GET') { return; }
    event.respondWith(
        caches.match(event.request).then(function(cached) {
            var networkFetch = fetch(event.request).then(function(response) {
                if (response && response.status === 200 && response.type === 'basic') {
                    var responseClone = response.clone();
                    caches.open(CACHE_NAME).then(function(cache) {
                        cache.put(event.request, responseClone);
                    });
                }
                return response;
            });
            return cached || networkFetch;
        })
    );
});
