// xcm-build-this
// XcaliburMoon Web Development Pricing - Build Tool
// Reads source files from src/, assets/, and config/, compiles a
// deployable self-contained package into deploy/this/.

package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"
)

const (
	version     = "1.0.0"
	srcDir      = "../src"
	assetsDir   = "../assets"
	configDir   = "../config"
	deployDir   = "../deploy/this"
	deployMeta  = "../deploy"
)

func main() {
	fmt.Printf("xcm-build-this v%s\n", version)
	fmt.Printf("Build started: %s\n", time.Now().Format(time.RFC1123))
	fmt.Println("---")

	steps := []struct {
		name string
		fn   func() error
	}{
		{"Prepare output directory",    prepareOutputDir},
		{"Copy PHP source files",        copyPHPSources},
		{"Copy and version assets",      copyAssets},
		{"Generate .htaccess",           generateHtaccess},
		{"Generate service worker",      generateServiceWorker},
		{"Write deploy README",          writeDeployReadme},
	}

	for _, step := range steps {
		fmt.Printf("  > %s... ", step.name)
		if err := step.fn(); err != nil {
			fmt.Println("FAILED")
			log.Fatalf("Build error in step '%s': %v", step.name, err)
		}
		fmt.Println("OK")
	}

	fmt.Println("---")
	fmt.Printf("Build complete. Deploy from: %s\n", filepath.Clean(deployDir))
}

func prepareOutputDir() error {
	if err := os.MkdirAll(filepath.Join(deployDir, "assets", "css"), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(deployDir, "assets", "js", "vendor"), 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(deployDir, "data"), 0755); err != nil {
		return err
	}
	return nil
}

func copyPHPSources() error {
	// Copy src/index.php -> deploy/this/index.php
	return copyFile(
		filepath.Join(srcDir, "index.php"),
		filepath.Join(deployDir, "index.php"),
	)
}

func copyAssets() error {
	// In a full build this step minifies CSS via Tailwind and hashes JS filenames.
	// This stub performs a direct copy for development verification.
	files := []struct{ src, dst string }{
		{filepath.Join(assetsDir, "css", "main.css"), filepath.Join(deployDir, "assets", "css", "main.css")},
		{filepath.Join(assetsDir, "js", "quote.js"),  filepath.Join(deployDir, "assets", "js", "quote.js")},
	}
	for _, f := range files {
		if err := copyFile(f.src, f.dst); err != nil {
			// Non-fatal for stub: file may not exist yet during first run
			fmt.Printf("(skipped: %s) ", filepath.Base(f.src))
		}
	}
	return nil
}

func generateHtaccess() error {
	content := `# XcaliburMoon Web Development Pricing
# Generated by xcm-build-this at ` + time.Now().Format(time.RFC1123) + `
# Do not edit this file directly.

Options -Indexes

<FilesMatch "\.(json|log|sqlite|sh|bak)$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order deny,allow
        Deny from all
    </IfModule>
</FilesMatch>

<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresDefault "access plus 1 month"
    ExpiresByType text/html "access plus 0 seconds"
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/javascript "access plus 1 year"
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [L,QSA]
</IfModule>
`
	return os.WriteFile(filepath.Join(deployDir, ".htaccess"), []byte(content), 0644)
}

func generateServiceWorker() error {
	buildHash := fmt.Sprintf("%x", time.Now().UnixNano())
	content := fmt.Sprintf(`// XcaliburMoon Service Worker
// Generated by xcm-build-this
// Build hash: %s

const CACHE_NAME = 'xcm-cache-%s';

const PRECACHE_URLS = [
    '/',
    '/assets/css/main.css',
    '/assets/js/quote.js',
];

self.addEventListener('install', function(event) {
    event.waitUntil(
        caches.open(CACHE_NAME).then(function(cache) {
            return cache.addAll(PRECACHE_URLS);
        }).then(function() {
            return self.skipWaiting();
        })
    );
});

self.addEventListener('activate', function(event) {
    event.waitUntil(
        caches.keys().then(function(cacheNames) {
            return Promise.all(
                cacheNames.filter(function(name) {
                    return name !== CACHE_NAME;
                }).map(function(name) {
                    return caches.delete(name);
                })
            );
        }).then(function() {
            return self.clients.claim();
        })
    );
});

self.addEventListener('fetch', function(event) {
    if (event.request.method !== 'GET') { return; }
    event.respondWith(
        caches.match(event.request).then(function(cached) {
            var networkFetch = fetch(event.request).then(function(response) {
                if (response && response.status === 200 && response.type === 'basic') {
                    var responseClone = response.clone();
                    caches.open(CACHE_NAME).then(function(cache) {
                        cache.put(event.request, responseClone);
                    });
                }
                return response;
            });
            return cached || networkFetch;
        })
    );
});
`, buildHash, buildHash)
	return os.WriteFile(filepath.Join(deployDir, "sw.js"), []byte(content), 0644)
}

func writeDeployReadme() error {
	content := fmt.Sprintf(`# XcaliburMoon Web Development Pricing - Deploy

**Build version**: %s
**Build timestamp**: %s

## Technologies Included

| Component         | Version / Notes                        |
|-------------------|----------------------------------------|
| PHP               | 8.3+ required on host                  |
| PHPMailer         | Latest via Composer                    |
| Math.js           | Self-hosted, see assets/js/vendor/     |
| Service Worker    | Generated by xcm-build-this            |

## Deployment Instructions

Upload the contents of this directory (deploy/this/) to the target folder on your server.
No build tools are required on the server. PHP 8.3+ and Apache or NGINX with rewrite support is all that is needed.

Store SMTP credentials and API keys outside the web root before going live.
`, version, time.Now().Format(time.RFC1123))
	return os.WriteFile(filepath.Join(deployMeta, "README.md"), []byte(content), 0644)
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0644)
}
